name: Actualizar Certificaciones Credly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"  # Se ejecuta cada 12 horas

jobs:
  update-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Actualizar badges desde Credly
        uses: GuillaumeFalourd/credly-badges-action@v1
        with:
          user_id: "202124087-angel-mondragon-gonzalez"
          format: "markdown"
          target_file: "README.md"

      - name: Commit y push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Insignias Credly actualizadas âœ¨"

